Разметка всех страниц
htmlacademy-htmlcss/2217509-gllacy-35 pull request #2
Opened 2022-09-28 10:05 UTC by MadonnaDuoEthil

- Стоит проверить, все ли в порядке с названиями классов
- Вопросы в комментариях к коду на строчках: 49, 55, 63
- Строчка 67: в коде-комментарии я расписала контент на двух других слайдах с главной страницы. Я не уверена, каким образом их надо вставить в код, чтобы получился нормальный слайдер. Прошу проверить расположение: тега <p>, картинок, кнопок.
- Комментарии на строках: 158
- Не всегда уверена, где вставлять неупорядоченный список, а где - таблицу. Список всегда идет в одну колонку? Взять, например, <section class="about"> (217 строка): тут подойдет список или нужна таблица из-за расположения элементов?
- Вопрос на строке 253

---
:mortar_board: [Разметка всех страниц](https://up.htmlacademy.ru/htmlcss/35/user/2217509/tasks/5)

2022-09-29 05:29 UTC, Safyann commented on index.html
> +          <!--Нужен ли здесь заголовок?-->
Да, нужен, так как это секция, а в ней должен быть заголовок

2022-09-29 05:40 UTC, Safyann commented on index.html
> +                  <a class="navigation_link" href="#">Каталог</a>
можно добавить еще один список с подменю

2022-09-29 06:23 UTC, Safyann requested changes
- у тебя много <p> используется как обертка чего-либо, лучше использовать тег div для этого, если не знаешь что поставить как обертку
- по классам ок
- я смотрела из списка один элемент и комментировала его, так как остальные должны иметь туже разметку, поэтому если видишь что есть комментарии у какого-либо li, то и остальные в этом списке надо будет поправить

2022-09-29 06:23 UTC, Safyann commented on index.html
> +          <!--Нужен ли здесь заголовок?-->
тут у тебя слайдер, каждый слайд - это элемент списка ul, то есть li содержит заголовок, текст, конпку и картинку

2022-09-29 06:23 UTC, Safyann commented on index.html
> +                  </button>
кнопки идут после слайдера, то есть после списка

2022-09-29 06:23 UTC, Safyann commented on index.html
> +              <img class="slide_photo" src="" alt="Карамельный пломбир с маршмеллоу (силуэт)"></p>
да, изображения контентные, так как можно выставить на сайт любое мороженное которое мы хотим продать

2022-09-29 06:23 UTC, Safyann commented on index.html
> +              <p class="slider_text"><h3>Нежный пломбир<br> с клубничным джемом</h3></p>
h3 нельзя вкладывать в тег p, так как p - это параграф и он рассчитан на тест описание, например возьми книгу там есть параграфы, заголовки разного уровня и посреди параграфа нет заголовков

2022-09-29 06:23 UTC, Safyann commented on index.html
> +              <p><img class="slide_photo_current" src="" alt="Нежный пломбир с клубничным джемом (основное)">
лишний <p>

2022-09-29 06:23 UTC, Safyann commented on index.html
> +              <p class="banner_title">Заказывайте мороженое и получайте подарки!</p>
для заголовка лучше использовать тег заголовка  h3, можно этот заголовок использовать как h2, а скрытый удалить

2022-09-29 06:23 UTC, Safyann commented on index.html
> +                          <p class="banner_item_title">Малинка даром!</p>
а вот тут заголовок h3

2022-09-29 06:23 UTC, Safyann commented on index.html
> +          <p class="popular_products_title">Попробуйте самые популярные вкусы нашего мороженого</p>
можно этот заголовок использовать как h2, а скрытый удалить

2022-09-29 06:23 UTC, Safyann commented on index.html
> +                  <!--Нужно ли здесь оформлять текст как подпись, через тег figure\figcaption?-->
нет, так как это не подпись изображения, а карточка товара

2022-09-29 06:23 UTC, Safyann commented on index.html
> +                          <a class="button button_order" href="#">
лучше сделать button, так как это действие добавить в корзину, а не переход на какую-либо страницу

2022-09-29 06:23 UTC, Safyann commented on index.html
> +      <!--Здесь нужен section?-->
да нужен

2022-09-29 06:23 UTC, Safyann commented on index.html
> +              <p class="sending_email_text"> Подпишитесь на нашу сладкую рассылку и будьте всегда<br>
<p> можно вынести из form

2022-09-29 06:23 UTC, Safyann commented on index.html
> +              <p class="sending_email_area">
лишний p, можно просто оставить <form> <input/> <button></button></form>

2022-09-29 06:23 UTC, Safyann commented on index.html
> +          <h3 class="delivery_heading">Доставка любимого мороженого на дом</h3>
можно как h2

2022-09-29 06:23 UTC, Safyann commented on index.html
> +                  <input class="button send_button" type="submit" name="delivery_data" placeholder="Отправить">
лучше button, так как input type="submit" считается устаревшим подходом

2022-09-29 06:23 UTC, Safyann commented on index.html
> +              <p class="delivery_user_form">
лишний p

2022-09-29 09:16 UTC, MadonnaDuoEthil commented on index.html
> +                  <a class="navigation_link" href="#">Каталог</a>
Это касается только каталога или таким же образом надо разметить "поиск", "вход" и "корзину"?

2022-10-02 04:18 UTC, Safyann commented on catalog.html
> +                    <!--В макете есть только опция "по популярности", нужно ли вставлять то, что ниже?-->
да, для примера неплохо добавить, лишним не будет

2022-10-02 04:23 UTC, Safyann approved these changes
принято, но есть маленькая опечатка с классом, потом поправь

2022-10-02 04:23 UTC, Safyann commented on catalog.html
> +            <ul products_list>
должно быть это был класс))

2022-10-02 04:23 UTC, merged