Добавляет фоновые картинки и лого htmlacademy в папку, стилевой файл styles.css и изменяет index. и .catalog
htmlacademy-htmlcss/2217509-gllacy-35 pull request #4
Opened 2022-10-12 09:30 UTC by MadonnaDuoEthil

INDEX.HTML
1. Добавляет класс <navigation_user_item> в навигации для удобства стилизации
2. Добавляет/переименовывает класс "dark"\"light" кнопкам для удобства стилизации
3. Меняет класс в заголовке 143 строчки, добавляет перенос <br>, как в макете
4. Добавляет перенос в заголовке 264 строчки, как в макете
5. Оборачивает 269-288 строчки в <div>, добавляет класс "delivery_form" в разделе "доставка" для удобства стилизации
6. Добавляет изображение с лого академии в футере (строка 348), как в макете
7. Добавлен класс "provider" (332 строчка) для удобства стилизации
8. В строках 292-293 поставила тег <p> вместо <h3>, т.к. заголовок было сложно стилизовать

?258 строка: как сделать value в input определенного цвета?

CATALOG.HTML
1. Подключает файл со стилями (6 строка)
2. Добавляет класс "button_apply button_dark" в 155 строке и "button_show_more button_dark" в 316 строке для удобства стилизации

STYLES.CSS
?В строках 166-172 (.about): как сделать одновременно белый фон и вафлю? То же самое с почтофоном в рассылке (208 строка)

2022-10-13 17:25 UTC, Safyann requested changes
Отлично, добавила пару пожеланий чтобы в дальнейшем было проще и ответила на вопросы в коде

2022-10-13 17:25 UTC, Safyann commented on styles/styles.css
> +body.pink {
можно для body выделить общие стили, а по классу оставить только цвет

2022-10-13 17:25 UTC, Safyann commented on index.html
>                  <input class="sending_subscription_email_field" type="email" name="user_email" value="email@example.com">
тут лучше не value а placeholder и стилизовать через псевдоэлемент ::placeholder https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder
а на будущее value это тоже текст и цвет в инпуте задается через color

2022-10-13 17:25 UTC, Safyann commented on styles/styles.css
> +    font-family: inherit;
можно не писать,  так как наследуется от body

2022-10-13 17:25 UTC, Safyann commented on styles/styles.css
> +}
Несколько вариантов:
1. можно добавить еще одну обертку, на пример about_content и у него белый фон, а about сделать padding 24px
2. почитать про псевдоэлементы ::before и ::after и можно посмотреть в их сторону

2022-10-13 17:25 UTC, Safyann commented on styles/styles.css
> +    height: 224px;
Жестко заданную высоту лучше не использовать, иначе если контента станет больше, то просто текст не влезет в компонент, лучше min-height, а height использовать только для изображений

2022-10-13 17:27 UTC, Safyann commented
В задании нужно стилизовать весь текстовый контент, то есть заголовки, параграфы и ссылки, ну и можно вставить фоновые изображения

2022-10-25 14:45 UTC, MadonnaDuoEthil commented on index.html
> +                <div class="about_content">
Вот тут добавила div для белого фона на вафле. Я глянула про before/after, но у меня почему-то не сработало. Мне кажется, станет понятнее, когда сделаю сетку, потому что штука интересная!

2022-10-25 14:45 UTC, MadonnaDuoEthil commented on index.html
> +            <div class="newsletter_content">
Тут div для белого фона в секции с рассылкой.

2022-10-25 14:46 UTC, MadonnaDuoEthil commented on index.html
> +            <div class="contacts_content">
Тут div для белого фона в секции с контактами и адресом.

2022-10-25 14:46 UTC, MadonnaDuoEthil commented on styles/styles.css
> +body {
Разделила body и pink.

2022-10-25 14:47 UTC, MadonnaDuoEthil commented on styles/styles.css
> -    font-family: inherit;
Удалила, потому что итак наследуется.

2022-10-25 14:48 UTC, MadonnaDuoEthil commented on styles/styles.css
> +    padding: 24px;
Добавила отступы у блока с вафлей

2022-10-25 14:48 UTC, MadonnaDuoEthil commented on styles/styles.css
> +.about_content {
Тут белый фон

2022-10-25 14:50 UTC, MadonnaDuoEthil commented on styles/styles.css
> -    width: 570px;
Везде удалила ширину и высоту, поменяв на проценты, как в скринкасте. Решила не добавлять минимальную, хотя и смущает внешний вид, но решила, что лучше сделать по шаблону, а потом на этапе с сеткой будет выглядеть нормально.

2022-10-25 14:50 UTC, MadonnaDuoEthil commented on styles/styles.css
> +input::placeholder {
Добавила цвет для placeholder-а.

2022-10-25 14:51 UTC, MadonnaDuoEthil commented on styles/styles.css
> +.newsletter_content {
Белый фон на блоке с рассылкой.

2022-10-25 14:52 UTC, MadonnaDuoEthil commented on styles/styles.css
> +.contacts_content {
Даже не помню, почему здесь был block, добавила корректный класс и сделала белый фон в блоке с контактами.

2022-10-26 15:42 UTC, merged